#!/usr/bin/env python3
"""
Create comprehensive YouTube ads ruleset for AeroGuard
"""
import json

# Critical YouTube ad blocking rules that are missing
critical_youtube_rules = [
    # YouTube ad endpoints
    {'id': 80001, 'priority': 1, 'action': {'type': 'block'}, 'condition': {'urlFilter': '||youtube.com/api/stats/ads*', 'resourceTypes': ['xmlhttprequest', 'fetch'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    {'id': 80002, 'priority': 1, 'action': {'type': 'block'}, 'condition': {'urlFilter': '||youtube.com/api/stats/qoe*', 'resourceTypes': ['xmlhttprequest', 'fetch'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    {'id': 80003, 'priority': 1, 'action': {'type': 'block'}, 'condition': {'urlFilter': '||youtube.com/ptracking*', 'resourceTypes': ['xmlhttprequest', 'fetch', 'ping'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    {'id': 80004, 'priority': 1, 'action': {'type': 'block'}, 'condition': {'urlFilter': '||youtube.com/pagead/*', 'resourceTypes': ['xmlhttprequest', 'fetch', 'subdocument'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    {'id': 80005, 'priority': 1, 'action': {'type': 'block'}, 'condition': {'urlFilter': '||youtube.com/get_video_info*&adformat=*', 'resourceTypes': ['xmlhttprequest', 'fetch'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    {'id': 80006, 'priority': 1, 'action': {'type': 'block'}, 'condition': {'urlFilter': '||youtube.com/get_video_info*&ad_type=*', 'resourceTypes': ['xmlhttprequest', 'fetch'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    {'id': 80007, 'priority': 1, 'action': {'type': 'block'}, 'condition': {'urlFilter': '||youtube.com/get_video_info*&ad3_module=*', 'resourceTypes': ['xmlhttprequest', 'fetch'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    {'id': 80008, 'priority': 1, 'action': {'type': 'block'}, 'condition': {'urlFilter': '||youtube.com/get_video_info*&afv_*', 'resourceTypes': ['xmlhttprequest', 'fetch'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    {'id': 80009, 'priority': 1, 'action': {'type': 'block'}, 'condition': {'urlFilter': '||youtube.com/get_video_info*&vmap=*', 'resourceTypes': ['xmlhttprequest', 'fetch'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    {'id': 80010, 'priority': 1, 'action': {'type': 'block'}, 'condition': {'urlFilter': '||youtube.com/get_video_info*&ad_tag=*', 'resourceTypes': ['xmlhttprequest', 'fetch'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    {'id': 80010, 'priority': 1, 'action': {'type': 'block'}, 'condition': {'urlFilter': '||youtube.com/get_video_info*&ad_url=*', 'resourceTypes': ['xmlhttprequest', 'fetch'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    {'id': 80011, 'priority': 1, 'action': {'type': 'block'}, 'condition': {'urlFilter': '||youtube.com/annotations_invideo*', 'resourceTypes': ['xmlhttprequest', 'fetch'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    {'id': 80012, 'priority': 1, 'action': {'type': 'block'}, 'condition': {'urlFilter': '||youtube.com/api/stats/watchtime*', 'resourceTypes': ['xmlhttprequest', 'fetch'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    {'id': 80013, 'priority': 1, 'action': {'type': 'block'}, 'condition': {'urlFilter': '||youtube.com/api/stats/heartbeat*', 'resourceTypes': ['xmlhttprequest', 'fetch'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    {'id': 80014, 'priority': 1, 'action': {'type': 'block'}, 'condition': {'urlFilter': '||youtube.com/api/stats/playback*', 'resourceTypes': ['xmlhttprequest', 'fetch'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    {'id': 80015, 'priority': 1, 'action': {'type': 'block'}, 'condition': {'urlFilter': '||youtube.com/youtubei/v1/player*', 'resourceTypes': ['xmlhttprequest', 'fetch'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    {'id': 80016, 'priority': 1, 'action': {'type': 'block'}, 'condition': {'urlFilter': '||youtube.com/youtubei/v1/next*', 'resourceTypes': ['xmlhttprequest', 'fetch'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    {'id': 80016, 'priority': 1, 'action': {'type': 'block'}, 'condition': {'urlFilter': '||youtube.com/youtubei/v1/browse*', 'resourceTypes': ['xmlhttprequest', 'fetch'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    {'id': 80017, 'priority': 1, 'action': {'type': 'block'}, 'condition': {'urlFilter': '||youtube.com/youtubei/v1/ad/*', 'resourceTypes': ['xmlhttprequest', 'fetch'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    {'id': 80018, 'priority': 1, 'action': {'type': 'block'}, 'condition': {'urlFilter': '||youtube.com/get_video*', 'resourceTypes': ['xmlhttprequest', 'fetch', 'subdocument'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    # Google ad domains on YouTube
    {'id': 80019, 'priority': 1, 'action': {'type': 'block'}, 'condition': {'urlFilter': '||doubleclick.net/*', 'resourceTypes': ['xmlhttprequest', 'fetch', 'subdocument', 'image', 'script'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    {'id': 80019, 'priority': 1, 'action': {'type': 'block'}, 'condition': {'urlFilter': '||googlesyndication.com/*', 'resourceTypes': ['xmlhttprequest', 'fetch', 'subdocument', 'image', 'script'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    {'id': 80020, 'priority': 1, 'action': {'type': 'block'}, 'condition': {'urlFilter': '||googleadservices.com/*', 'resourceTypes': ['xmlhttprequest', 'fetch', 'subdocument', 'image', 'script'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    {'id': 80021, 'priority': 1, 'action': {'type': 'block'}, 'condition': {'urlFilter': '||googletagmanager.com/*', 'resourceTypes': ['xmlhttprequest', 'fetch', 'script'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    {'id': 80022, 'priority': 1, 'action': {'type': 'block'}, 'condition': {'urlFilter': '||googletagservices.com/*', 'resourceTypes': ['xmlhttprequest', 'fetch', 'script'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    {'id': 80022, 'priority': 1, 'action': {'type': 'block'}, 'condition': {'urlFilter': '||pagead2.googlesyndication.com/*', 'resourceTypes': ['xmlhttprequest', 'fetch', 'subdocument', 'image', 'script'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    {'id': 80023, 'priority': 1, 'action': {'type': 'block'}, 'condition': {'urlFilter': '||pubads.g.doubleclick.net/*', 'resourceTypes': ['xmlhttprequest', 'fetch', 'subdocument', 'image', 'script'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    {'id': 80023, 'priority': 1, 'action': {'type': 'block'}, 'condition': {'urlFilter': '||securepubads.g.doubleclick.net/*', 'resourceTypes': ['xmlhttprequest', 'fetch', 'subdocument', 'image', 'script'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    {'id': 80024, 'priority': 1, 'action': {'type': 'block'}, 'condition': {'urlFilter': '||adservice.google.com/*', 'resourceTypes': ['xmlhttprequest', 'fetch', 'subdocument', 'image', 'script'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    # IMA SDK
    {'id': 80025, 'priority': 1, 'action': {'type': 'block'}, 'condition': {'urlFilter': '||imasdk.googleapis.com/*', 'resourceTypes': ['script', 'xmlhttprequest', 'fetch'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    {'id': 80026, 'priority': 1, 'action': {'type': 'block'}, 'condition': {'urlFilter': '||imasdk.s3.amazonaws.com/*', 'resourceTypes': ['script', 'xmlhttprequest', 'fetch'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    # YouTube ad player JS
    {'id': 80027, 'priority': 1, 'action': {'type': 'block'}, 'condition': {'urlFilter': '||s.ytimg.com/yts/jsbin/player-*ad*', 'resourceTypes': ['script'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    {'id': 80027, 'priority': 1, 'action': {'type': 'block'}, 'condition': {'urlFilter': '||s.ytimg.com/yts/jsbin/*ima*', 'resourceTypes': ['script'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    {'id': 80028, 'priority': 1, 'action': {'type': 'block'}, 'condition': {'urlFilter': '||s.ytimg.com/yts/jsbin/*ads*', 'resourceTypes': ['script'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    # Ad subdomains
    {'id': 80028, 'priority': 1, 'action': {'type': 'block'}, 'condition': {'urlFilter': '||ads.youtube.com/*', 'resourceTypes': ['xmlhttprequest', 'fetch', 'subdocument', 'image', 'script'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    {'id': 80029, 'priority': 1, 'action': {'type': 'block'}, 'condition': {'urlFilter': '||advertising.youtube.com/*', 'resourceTypes': ['xmlhttprequest', 'fetch', 'subdocument', 'image', 'script'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    {'id': 80029, 'priority': 1, 'action': {'type': 'block'}, 'condition': {'urlFilter': '||partneradvertising.youtube.com/*', 'resourceTypes': ['xmlhttprequest', 'fetch', 'subdocument', 'image', 'script'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    # Tracking pixels
    {'id': 80030, 'priority': 1, 'action': {'type': 'block'}, 'condition': {'urlFilter': '||googleads.g.doubleclick.net/pagead/viewthroughconversion/*', 'resourceTypes': ['image', 'ping'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    {'id': 80031, 'priority': 1, 'action': {'type': 'block'}, 'condition': {'urlFilter': '||googleads.g.doubleclick.net/pagead/conversion/*', 'resourceTypes': ['image', 'ping'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    {'id': 80031, 'priority': 1, 'action': {'type': 'block'}, 'condition': {'urlFilter': '||www.googleadservices.com/pagead/conversion/*', 'resourceTypes': ['image', 'ping'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    {'id': 80032, 'priority': 1, 'action': {'type': 'block'}, 'condition': {'urlFilter': '||doubleclick.net/activity/*', 'resourceTypes': ['image', 'ping'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    {'id': 80032, 'priority': 1, 'action': {'type': 'block'}, 'condition': {'urlFilter': '||fls.doubleclick.net/activityi/*', 'resourceTypes': ['image', 'ping'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    {'id': 80033, 'priority': 1, 'action': {'type': 'block'}, 'condition': {'urlFilter': '||ad.doubleclick.net/activity/*', 'resourceTypes': ['image', 'ping'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    # ALLOW rules for video playback
    {'id': 90001, 'priority': 2, 'action': {'type': 'allow'}, 'condition': {'urlFilter': '||googlevideo.com/videoplayback*', 'resourceTypes': ['media'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    {'id': 90002, 'priority': 2, 'action': {'type': 'allow'}, 'condition': {'urlFilter': '||*.googlevideo.com/*', 'resourceTypes': ['media'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    {'id': 90003, 'priority': 2, 'action': {'type': 'allow'}, 'condition': {'urlFilter': '||youtube.com/api/stats/watchtime*', 'resourceTypes': ['xmlhttprequest', 'fetch'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    {'id': 90004, 'priority': 2, 'action': {'type': 'allow'}, 'condition': {'urlFilter': '||s.ytimg.com/yts/jsbin/player-*', 'resourceTypes': ['script'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    {'id': 90005, 'priority': 2, 'action': {'type': 'allow'}, 'condition': {'urlFilter': '||s.ytimg.com/yts/jsbin/www-embed-player*', 'resourceTypes': ['script'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    {'id': 90006, 'priority': 2, 'action': {'type': 'allow'}, 'condition': {'urlFilter': '||i.ytimg.com/*', 'resourceTypes': ['image'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    {'id': 90010, 'priority': 2, 'action': {'type': 'allow'}, 'condition': {'urlFilter': '||yt3.ggpht.com/*', 'resourceTypes': ['image'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    {'id': 90010, 'priority': 2, 'action': {'type': 'allow'}, 'condition': {'urlFilter': '||youtube.com/api/timedtext*', 'resourceTypes': ['xmlhttprequest', 'fetch'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    {'id': 90011, 'priority': 2, 'action': {'type': 'allow'}, 'condition': {'urlFilter': '||youtube.com/youtubei/v1/player*', 'resourceTypes': ['xmlhttprequest', 'fetch'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    {'id': 90011, 'priority': 2, 'action': {'type': 'allow'}, 'condition': {'urlFilter': '||youtube.com/youtubei/v1/next*', 'resourceTypes': ['xmlhttprequest', 'fetch'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    {'id': 90012, 'priority': 2, 'action': {'type': 'allow'}, 'condition': {'urlFilter': '||youtube.com/youtubei/v1/browse*', 'resourceTypes': ['xmlhttprequest', 'fetch'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    {'id': 90013, 'priority': 2, 'action': {'type': 'allow'}, 'condition': {'urlFilter': '||youtube.com/youtubei/v1/live_chat*', 'resourceTypes': ['xmlhttprequest', 'fetch'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
    {'id': 90014, 'priority': 2, 'action': {'type': 'allow'}, 'condition': {'urlFilter': '||youtube.com/youtubei/v1/comment*', 'resourceTypes': ['xmlhttprequest', 'fetch'], 'initiatorDomains': ['youtube.com', 'youtube-nocookie.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com', 'tv.youtube.com']}},
]

# Write YouTube ads ruleset
with open('rules/youtube_ads.json', 'w') as f:
    json.dump(critical_youtube_rules, f, indent=2)

print(f'Created {len(critical_youtube_rules)} YouTube ads rules')