// Final comprehensive check: syntax, assets, manifest integrity
const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');
const root = 'C:/Users/PC/Documents/AeroGaurd';
let fails = 0;

// 1. node --check every JS file the extension ships
function walk(dir, out = []) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    if (['node_modules', '.git', '_metadata', 'tests', 'icons'].includes(e.name)) continue;
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walk(p, out);
    else if (/\.(js|mjs)$/.test(e.name)) out.push(p);
  }
  return out;
}
for (const f of walk(root)) {
  try {
    execSync(`node --check "${f}"`, { stdio: 'pipe' });
  } catch (e) {
    fails++;
    console.log('SYNTAX FAIL:', path.relative(root, f));
    console.log(String(e.stderr).split('\n').slice(0, 4).join('\n'));
  }
}
console.log('1. syntax check: ' + (fails === 0 ? 'ALL OK' : fails + ' failures'));

// 2. manifest integrity
const m = JSON.parse(fs.readFileSync(path.join(root, 'manifest.json'), 'utf8'));
const rs = m.declarative_net_request.rule_resources;
console.log(`2. manifest: ${rs.length} rulesets listed, ${rs.filter(r => r.enabled).length} enabled (limits: 50 listed/enabled)`);
if (rs.length > 50 || rs.filter(r => r.enabled).length > 50) { fails++; console.log('   LIMIT EXCEEDED'); }
console.log('   minChrome:', m.minimum_chrome_version, '| WAR:', m.web_accessible_resources[0].resources.join(', '));

// 3. PNG icons valid
for (const icon of Object.values(m.icons)) {
  const buf = fs.readFileSync(path.join(root, icon));
  const ok = buf.length > 100 && buf[0] === 0x89 && buf[1] === 0x50 && buf[2] === 0x4e && buf[3] === 0x47;
  if (!ok) { fails++; console.log('ICON INVALID:', icon); }
}
console.log('3. icons: PNG headers OK');

// 4. locales
const msgs = JSON.parse(fs.readFileSync(path.join(root, '_locales/en/messages.json'), 'utf8'));
const used = new Set();
JSON.stringify(m).replace(/__MSG_(\w+)__/g, (_, k) => used.add(k));
const missingMsgs = [...used].filter(k => !msgs[k]);
if (missingMsgs.length) { fails++; console.log('LOCALE MISSING:', missingMsgs); }
console.log('4. locales:', used.size, 'manifest keys used, all present');

// 5. all referenced files exist (re-check post-build)
const refs = [m.background.service_worker, m.action.default_popup, m.options_page,
  ...m.content_scripts.flatMap(cs => [...cs.js, ...(cs.css || [])]),
  ...rs.map(r => r.path),
  ...Object.values(m.icons), ...Object.values(m.action.default_icon)];
const missing = [...new Set(refs)].filter(f => !fs.existsSync(path.join(root, f)));
if (missing.length) { fails++; console.log('MISSING FILES:', missing); }
console.log('5. referenced files: ' + (missing.length === 0 ? 'all exist' : missing.join(', ')));

// 6. welcome/help pages
for (const f of ['welcome.html', 'help/help.html']) {
  if (!fs.existsSync(path.join(root, f))) { fails++; console.log('MISSING PAGE:', f); }
}
console.log('6. welcome.html + help/help.html: exist');

// 7. cosmetic shards
const cosDir = path.join(root, 'rules/cosmetic');
const shards = fs.readdirSync(cosDir).filter(f => f.endsWith('.json'));
const genSize = fs.statSync(path.join(cosDir, 'generic.json')).size;
console.log(`7. cosmetic shards: ${shards.length} files, generic.json ${(genSize / 1024).toFixed(0)}KB`);
if (genSize < 1000) { fails++; console.log('   generic.json suspiciously small'); }

// 8. Chrome reserved names: "_locales" is the only author-facing reserved name.
//    "_metadata" is generated BY Chrome itself for declarativeNetRequest
//    extensions on every load - it reappears constantly and is tolerated.
//    "_platform_specific" is also reserved-and-allowed. Anything else fails.
const ALLOWED_UNDERSCORE = new Set(['_locales', '_platform_specific', '_metadata']);
const illegal = fs.readdirSync(root, { withFileTypes: true })
  .filter(e => e.name.startsWith('_') && !ALLOWED_UNDERSCORE.has(e.name))
  .map(e => e.name);
if (illegal.length) { fails++; console.log('RESERVED NAMES at root (rename/remove):', illegal.join(', ')); }
console.log('8. reserved-name check: ' + (illegal.length === 0 ? 'root clean' : illegal.join(', ')));

console.log('\nFINAL: ' + (fails === 0 ? 'ALL CHECKS PASS' : fails + ' FAILURES'));
process.exit(fails === 0 ? 0 : 1);
